### ISSUE TITLE
Question: Do not use One PHP if You are building big full stack projects

### ISSUE THREAD

**Issue by sebastienratez** [juliomatcom/one-file-php-framework#5]
Could you say why?

Thank you

**Comment by juliomatcom** [comment]
Hi @sebastienratez, because it's simple in its core, OnePHP do not provides important things for big projects like a pre-installed ORM (like Doctrine), or full feature template system like ie: Twig, form validations, vendors, etc.
Instead you will need to implement or install them by hand, so it fits better in small projects with fewer dependencies. The cool thing with OnePHP is that **you do not add anything you don't want or need in your application, it's minimalist or a micro-framework**. 
Let me know if any doubt, :wink:

**Comment by sebastienratez** [comment]
Hey! Thanks for the feedback. 

From a certain perspective (mine at least), your answer is in fact backing up the complete opposite statement: to me it seems I _should_ be using your framework. I have my own ORM, all I need is a light and community supported rest framework.

Now my real concern is more in terms of bugs and performance. Is there any reason why, from this angle, I should be careful when using your work? Again, I'm only reacting to your statement "Do not use One PHP if You are building big full stack projects" ;)

Thanks again, I'm anyway already implementing it so I'll give you feedback when I can.

Regards

**Comment by juliomatcom** [comment]
Hey, you do understand me,
For what you said sounds like you  already have the others tools, so in your case it should work perfect, it will not get in your way.

> Now my real concern is more in terms of bugs and performance. Is there any reason why, from this angle, I should be careful when using your work?

My statement is not because of less performance or bugs  :+1:  in fact it is super fast because the way is built (basically a router, please don't hesitate to look at the source code is pretty straightforward).
Is all about **use the tools that fits you best**, in my own experience OnePHP fits better in restful APIs and to build quick web apps.

Hope it works well for you,
Regards!
